### ISSUE TITLE
ECS Prerelease 2024-10-03: undefined variable - maybe update function running before the init function

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#2182] opened 2024-10-03 13:12 UTC
I get this error when running the Escape scenario:
![Screenshot 2024-10-03 at 8 00 31 AM](https://github.com/user-attachments/assets/b84dcec8-3914-458f-ad3b-ab0597f9513b)
The line in the scenario code is `bobsx, bobsy = vectorFromAngle(stationWig.angle,3000)` which is the first executable line in the `update` function. Looking back to where `stationWig` is defined, it's defined in the `buildNearbyStations` function, line 572, which is called by the `init` function, line 68. I'm not sure what might cause this other than maybe the `update` function is getting called before the `init` function has been completed. I also notice that we did not get the player ship spawned and that additional player ships were not restricted (`init` function, lines 145 and 146) based on the screen that was reached with the "Waiting for server to spawn a ship" line present and the player ship selection widget active below it.

**Comment by daid** [comment] 2024-10-06 18:30
```
[ERROR   ]: LUA-Error:scenario_53_escape.lua:301: attempt to call a nil value (global 'queryScienceDatabase')
stack traceback:
        scenario_53_escape.lua:30: in function <scenario_53_escape.lua:24>
```
Happens in init before that. So likely a duplicate of #2187

**Closed** 2024-10-07 18:00 UTC
