### ISSUE TITLE
REQUEST: Mac Build

### ISSUE THREAD

**Issue by unknowndomain** [daid/EmptyEpsilon#384] opened 2016-08-09 16:30 UTC
Was wondering if you might consider a downloadable Mac build with the SFML framework incorporated.

**Comment by oznogon** [comment] 2016-08-09 19:07
Per [daid](https://github.com/daid/EmptyEpsilon/issues/286#issuecomment-224206852), this seems unlikely. I'm maintaining an OS X fork at [oznogon/EmptyEpsilon](https://github.com/oznogon/EmptyEpsilon), but it doesn't yet incorporate SFML, I'm inexperienced with OS X development, and it's a low priority.

**Comment by daid** [comment] 2016-08-10 14:14
You can blame Apple for there not being a Mac build. They made life for cross platform developers pretty much a hell.

**Comment by kwadroke** [comment] 2016-08-10 14:38
Could something like Travis-CI help with this? Looks like they can build for [OSX](https://docs.travis-ci.com/user/osx-ci-environment/).

**Comment by aaroneiche** [comment] 2016-08-30 22:39
Can you clarify on what the difficulty is? I'd like to contribute if I can, maybe I can push things along on the Mac front.

**Comment by daid** [comment] 2016-08-31 05:51
a) You cannot build Mac software on anything but a Mac. (And I don't have any)
b) Getting a build that runs on other systems then your own is difficult. Which makes the requirement that you have two macs, preferably with different OSX versions.
c) Apple has no problem in silently updating your compiler and thus breaking your build.
d) The newer version OSX you have the harder it is to build for older versions.
e) Virtualization? Apple says: fuck you.

**Comment by emacsen** [comment] 2016-09-02 18:23
@daid I agree with you in the sense of "Fuck Apple" but asking OSX users to build their own seems like a sub-optimal solution. How does commercial software handle b?

**Comment by mrozbarry** [comment] 2016-10-11 23:25
I've got a mac, and I'm a developer.  @daid, If I create builds, what do I need to do to get them hosted by yourself?  I'll see what I can do about setting up a script that checks for a new release and does a local build.

**Comment by mrozbarry** [comment] 2016-10-11 23:28
To expand, I've got a 2014 Mac running El Captain (10.11.6), xcode 7.3.1, and minimal experience with xcode. I'm mostly a linux dev (one of those sickos who uses vim+command line), so I'm not an xcode pro, but I'll figure this out.

**Comment by mrozbarry** [comment] 2016-10-11 23:36
@daid @oznogon what sort of process do we need to merge/PR in the osx changes?  Looks like a few source tweaks, mostly with blending.

**Comment by Fouindor** [comment] 2016-10-29 09:29
The latest SFML version, 2.4, seems to have extensive Mac code overhaul to fix long standing issues. It may be useful to see if the Mac bug is solved by this new version.

**Comment by teamcoltra** [comment] 2016-11-19 09:43
+1

**Comment by oznogon** [comment] 2016-11-27 08:03
@mrozbarry I no longer have a Mac and cannot build. The biggest issues were largely with blend modes and keyboard handling, so I'm also extremely curious if SFML 2.4 resolves them.

**Comment by dan-frohlich** [comment] 2017-01-06 21:06
I have a mac and have built latest from master. I'd like to help.  @daid

**Comment by amir-arad** [comment] 2017-02-19 19:42
I've just built latest from master, following the instructions from the wiki, but the app doesn't work on my machine. in debug mode I get this message:
```An internal OpenGL call failed in RenderTarget.cpp (278) : GL_INVALID_FRAMEBUFFER_OPERATION, the object bound to FRAMEBUFFER_BINDING is not "framebuffer complete"```
Macbook pro, OSX Yosemite 10.10.5

**Comment by HenriVesala** [comment] 2017-04-21 18:24
@jozan and I made that wiki OS X instruction about year ago. 
It worked back in the days without serious problems. 
Now we need someone smarter to sort this out.

**Comment by jacob-israel-turner** [comment] 2018-09-11 22:42
Hey guys, is there any word on MacOS compatibility of any kind?  I'd even settle for a set of build instructions.  I have a Windows machine, but gathering enough devices for 6 people is a bit tough without being able to use Macs.

If I can be of any help setting up an automated build of any sort, I'm happy to help as well.  I am a software engineer, though only with a bit of experience in XCode.

**Comment by aaroneiche** [comment] 2018-09-11 23:08
I haven't tried to build this in a while, so I can't speak to that -  but the difficulties with the Mac build are becoming even more difficult. Apple is deprecating it's (admittedly lousy) OpenGL support in favor of Metal. I would suggest your best shot is trying to get it to run on a Windows or Linux VM.

**Comment by amir-arad** [comment] 2018-09-12 05:39
[wine](https://www.winehq.org/) generally works fine for my crew at the office, and so do the mac builds that i make locally (though the mac build requires `brew install sfml` on the station machine in order to run)

**Comment by jacob-israel-turner** [comment] 2018-09-12 16:20
Awesome, I'll give wine a try. I'll have a Windows machine to host, so should be good there. Thanks guys.

**Comment by daid** [comment] 2018-09-12 17:46
> I've just built latest from master, following the instructions from the wiki, but the app doesn't work on my machine. in debug mode I get this message:
> `An internal OpenGL call failed in RenderTarget.cpp (278) : GL_INVALID_FRAMEBUFFER_OPERATION, the object bound to FRAMEBUFFER_BINDING is not "framebuffer complete"`
> Macbook pro, OSX Yosemite 10.10.5

That could be an SFML bug, you might want to search for SFML and RenderTexture for known problems on that area.

**Comment by oznogon** [comment] 2020-02-15 01:53
I've recently gotten my hands on a Mac still running Mojave and have successfully built EE from master using the [wiki instructions](https://github.com/daid/EmptyEpsilon/wiki/Build-from-sources#os-x) and Homebrew's SFML 2.5.1. The build reports being 64-bit so it should work on Catalina; I'll have access to a separate machine running Catalina at some point to test whether it's buildable and runnable there.

Notably, in a quick run most of the graphics and stability issues reported in this thread or that I had experienced years back are not present. Only a couple minor glitches that don't affect game play, mostly artefacts in text rendering.

**Comment by oznogon** [comment] 2020-02-16 12:19
Now that I have a hardware Mac, I also have what I need to virtualize one, so I can now automatically build for macOS, Android, Linux .deb, and Windows from a couple of scripts. I'll try to build all of them tomorrow and if I can automate it, I'll stand up an unofficial build host.

**Comment by oznogon** [comment] 2020-02-17 03:08
I've scripted builds of 2020.01.15 releases and posted them here: https://oznogon.com/ee/

**Comment by daid** [comment] 2020-02-17 06:13
I thought virtual OSX was not allowed?

**Comment by oznogon** [comment] 2020-02-17 06:39
VirtualBox has supported macOS/OS X guests on OS X hosts since 3.2: https://www.virtualbox.org/manual/ch03.html#intro-macosxguests

**Comment by aaroneiche** [comment] 2020-02-17 06:44
I believe that virtualizing of macOS is allowed by the license on Apple Hardware.

**Comment by unknowndomain** [comment] 2020-02-18 17:58
It is but only on Apple Hardware and only for single user purposes, not for Citrix type setups.

**Comment by oznogon** [comment] 2020-02-18 19:03
Yeah — point is it's enough for me to automate and test builds on a reproducible clean system across multiple macOS versions.

**Comment by unknowndomain** [comment] 2020-02-18 19:33
@oznogon my understanding this is one of the main purposes that Apple permits this for, i.e for developers.

**Comment by unknowndomain** [comment] 2020-02-18 19:48
macOS Catalina [EULA](https://www.apple.com/legal/sla/docs/macOSCatalina.pdf)

Section 2Biii:
> you are granted a limited, non-transferable, non-exclusive license:
> to install, use and run up to two (2) additional copies or instances of the Apple Software within virtual operating system environments on each Mac Computer you own or control that is already running the Apple Software, for purposes of: (a) software development; (b) testing during software development; (c) using macOS Server; or (d) personal, non-commercial use.

> The grant set forth in Section 2B(iii) above does not permit you to use the virtualized copies or instances of the Apple Software in connection with service bureau, time-sharing, terminal sharing or other similar types of services.

This is identical in:
- macOS Mojave
- macOS High Sierra
- macoS Sierra

The wording is near identical, barring the operating system name change from OS X to macOS in:
- OS X (El Capitan)
- OS X (Yosemite)
- OS X (Mavericks)
- OS X (Mountain Lion)

After which the wording of section 2Biii is simplified to:

> to install, use and run up to two (2) additional copies or instances of the Apple Software within virtual operating system environments on each Mac Computer you own or control that is already running the Apple Software.

Which is a broader use than later released.

This is true in OS X (Lion) only.

The EULA for OS X Snow Leopard does not cover this at all that I can see, and Apple doesn't have the EULAs for prior operating systems published.

**Comment by oznogon** [comment] 2020-02-18 22:57
Successfully tested a four-platform 20200115 game (macOS server and client, with Windows, Android, and Ubuntu clients connected over the LAN) yesterday, ran Basic from start to finish with a main screen and audio. Will build the new batch tonight and do a similar test this weekend.

**Comment by oznogon** [comment] 2020-02-18 22:58
I think we can probably close this ticket — everything necessary to build on macOS is present and unofficial builds are possible (and now exist) to fulfill this request.

**Comment by oznogon** [comment] 2020-02-19 02:01
Built 2020.02.18 and published to my fork at https://github.com/oznogon/EmptyEpsilon/releases/tag/EE-2020.02.18

**Comment by daid** [comment] 2020-02-19 06:15
Yes. Unofficial mac builds are the only solution right now, unless someone donates me a Mac.

**Closed by daid** 2020-02-19 06:15 UTC

**Comment by oznogon** [comment] 2024-12-01 18:14
Since this closed issue is still the top search-engine result for queries like `emptyepsilon macos build instructions`, the current home of those instructions is the [Build - macOS article](https://github.com/daid/EmptyEpsilon/wiki/Build-%E2%80%90-macOS) on this repo's wiki

**Comment by vpelss** [comment] 2024-12-22 01:34
It is probably easier to boot up a mac with a portable usb linux distro and install to run the game. I am kind of sorry I turned my old macbook into a chromebook. Maybe I will image it as a mac again and try the build.
