### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#57] opened 2015-11-13 05:23 UTC
I am not able to connect to a server on the same PC or on another PC. I can see the server in the server list, but it just sits at "Connecting..."

I've compiled EE under Debian Linux using CMake for Win32 and Linux as well as under Windows 7 using CodeBlocks for Win32 with the same results. I was able to get it to build using the new Crash Logger.

When running the build under Linux for Win32, I've seen errors about not being able to bind to port 35667. Not sure if this is related.

**Comment by kwadroke** [comment] 2015-11-13 05:48
I ran netstat and the server is listening on port 35666. I built a debug version and the client reports 
 ```
[INFO] ScannerServer::New server: 127.0.0.1 35666 Server
[INFO] ScannerServer::New server: 192.168.1.18 35666 Server
```

I don't see anything from the server console. 

It seems like the server isn't acknowledging that it's getting a connection.

**Comment by kwadroke** [comment] 2015-11-13 06:18
Actually, I just found the problem or at least a problem. 
It's a problem in SeriousProton, file src/multiplayer_client.cpp, line 35. _status_ is never equal to ReadyToConnect. It's equal to **1**.

**Comment by daid** [comment] 2015-11-13 10:47
Actually, state is an enum, and enum have number values that match "identifier" values. ReadyToConnect however is 0, not 1. The problem is in the constructor of that code. And yes, I screwed up. But the code was not broken before.

**Comment by daid** [comment] 2015-11-13 10:47
(fixed in serious proton source)

**Closed by daid** 2015-11-13 10:47 UTC

**Comment by kwadroke** [comment] 2015-11-13 15:24
Ok. that works. All I know is I had the logger spit out the status and I only saw integers. I'm not that good with C/C++.

**Comment by daid** [comment] 2015-11-13 15:43
Guess you learned something new today :-)
