### ISSUE TITLE
BUG : Server creation screen hangs when reselecting Internet play

### ISSUE THREAD

**Issue by Fouindor** [daid/EmptyEpsilon#209] opened 2016-05-03 08:55 UTC
Hello, I've noticed a weird hang on server creation screen : When you switch from LAN => Internet => LAN => Internet, EE hangs and must be closed manually.

Present on releases : 
30/04/2016
28/04/2016
12/04/2016

**Comment by Fouindor** [comment] 2016-05-03 12:02
Furthermore, if I launch an Internet play and afterwards closing it, the application freezes in a similar fashion.
I'm usually on a " locked " network, which means I can not redirect ports or do much stuff on the network, which may make the registration to main server fail.

However, examining the log, no registration error is reported, so it means that neither of these events get fired up :
            LOG(WARNING) << "Failed to register at master server (" << response.getStatus() << ")";
            LOG(WARNING) << "Master server reports error on registering: " << response.getBody();

So far I've replicated this hang using 2 PC (using windows 7) on 2 different networks (both are quite locked).

**Comment by Fouindor** [comment] 2016-05-03 12:38
If, after setting internet server, I do nothing, I have :

[INFO]  Registering at master server
[WARN]  Master server reports error on registering: CONNECT FAILED: ***********:35666 (censored IP)

And I can close just fine.

It seems that stopping the server while trying to register makes the game hang.

**Comment by daid** [comment] 2016-05-03 15:13
[WARN] Master server reports error on registering: CONNECT FAILED: ***********:35666 (censored IP)

Means you do not have port forwarding setup properly, and thus your internet server cannot be reached.

**Comment by oznogon** [comment] 2016-06-06 01:09
I also can reproduce the crashing issue in the original post by cycling the LAN/Internet server selector as a client at least twice, most frequently after at least 3 cycles or when clicking the center of the selector and choosing an entry from the list. This consistently brings EE to a halt on Windows and doesn't generate a RPT file. 

This happens regardless of whether I'm running any EE servers, and I have no problems running internet servers or reaching internet-hosted servers running elsewhere.

**Comment by oznogon** [comment] 2016-07-01 18:10
I can also reproduce the crash on OS X and Linux.

**Comment by gcask** [comment] 2021-03-14 18:43
I have tried several attempts, with or without an internet connection active and could not reproduce.

Maybe we could close this one?

**Comment by daid** [comment] 2021-03-16 08:20
Yeah, I think this was fixed a while back.

**Closed** 2021-03-16 08:20 UTC
