### ISSUE TITLE
GM zoom out out after Main Screen view causes crash

### ISSUE THREAD

**Issue by nigelkennington** [daid/EmptyEpsilon#766] opened 2020-03-02 10:24 UTC
On version 2020.02.18-win32

Replication:

1. Select Scenario "Empty Space"
2. Spawn a standard Atlantis
3. Select "Main Screen" and "Ready"
4. Escape back to Station Selection Screen
5. Select "Game Master" and "Ready"
6. Use Mouse Wheel to zoom out map view.
7. Crash.

emptyepsilon.log does not show any relevant error messages but I've attached it anyway

[EmptyEpsilon.log](https://github.com/daid/EmptyEpsilon/files/4274780/EmptyEpsilon.log)

**Comment by daid** [comment] 2020-03-02 12:43
Did it produce an EmptyEpsilong.RPT file? That contains the information related to crashes.

**Comment by nigelkennington** [comment] 2020-03-02 13:38
It did. I've added .txt on the end so I can upload it.

[EmptyEpsilon.RPT.txt](https://github.com/daid/EmptyEpsilon/files/4275669/EmptyEpsilon.RPT.txt)

**Comment by daid** [comment] 2020-03-02 14:54
Thanks.

It looks like it is crashing somewhere in some rendering code. As the actual crash is inside the nvidea libraries. Quick google says that this can happen on certain render calls with invalid state. How far are you zooming out before it crashes?

**Comment by nigelkennington** [comment] 2020-03-02 15:10
Three "clicks" of the mouse wheel.

**Comment by nigelkennington** [comment] 2020-03-02 15:11
Three "clicks" of the mouse wheel.

**Comment by oznogon** [comment] 2020-03-02 17:40
I can't measure zoom wheel clicks, what does the zoom slider read after each click?

**Comment by nigelkennington** [comment] 2020-03-02 18:48
There isn't a zoom slider on the GM screen.

**Comment by oznogon** [comment] 2020-03-03 00:02
Haven't been able to reproduce with the given steps in a master branch build on 2018 MBP on macOS 10.15 with Radeon Pro 560X or Intel UHD 630, or Acer Spin 5 on Windows 10 with NVIDIA GTX 1050 or Intel UHD 620, but I don't have a mouse wheel that clicks.

**Comment by nigelkennington** [comment] 2020-03-03 10:03
If it helps, I took it into work today and tested it on a Windows 10 with a GeForce GTX 770 and that crashed as above but on a Windows 10 all in 1 with an onboard Intel 4600, it didn't.

**Comment by daid** [comment] 2020-03-03 10:31
This could be driver version specific. My machine has a GTX 1050TI, so I expect the same results as oznogon.

Big problem in figuring out the cause, is that the commands in the driver are queued, and the crash happens when this queue is executed. So the crash report doesn't point that the root cause.

**Comment by amir-arad** [comment] 2020-03-03 15:24
I think I've encountered this before here: amir-arad/EmptyEpsilon#28 . 
Still haven't gotten to pin-point it or fix it, but I've written my findings and thoughts there.

**Comment by oznogon** [comment] 2020-03-04 04:18
Bought a mouse with a wheel that clicks when turned, and tried again with daid's 20200115 and 20200218 builds and my master branch build on the Spin 5/NVIDIA GTX 1050. Can't reproduce. Driver is the GeForce Game Ready Driver v442.50 released 2020-02-27.

Does it matter which scenario it is? I can't reproduce with Empty Space and also tried in Basic.

**Comment by NinjaSpectre** [comment] 2020-03-05 02:03
I was able to reproduce this crash on a Windows 10 machine with a NVIDIA GeForce GTX 950.
I have come up with a fix that prevents this crash (at least on this machine) from happening.
I'll create a pull request once some others here confirm it is fixed (and no other bugs introduced).
[This zip file ](https://github.com/NinjaSpectre/EmptyEpsilon/releases/download/zoom-fix/EmptyEpsilon-fe8c5c97-win32-fix.zip)contains the win32 binary compiled from current master  and the libraries used.

**Comment by oznogon** [comment] 2020-03-05 02:46
@NinjaSpectre What NVIDIA driver/version?

**Comment by NinjaSpectre** [comment] 2020-03-05 19:14
The access violation happened for me with the 442.19 and 442.50 Game Ready Driver from NVIDIA.  It may be that this access violation doesn't happen on Pascal or newer GPUs.

**Comment by oznogon** [comment] 2020-03-06 23:36
@NinjaSpectre's PR is #768.

**Comment by oznogon** [comment] 2020-03-09 08:29
#768 was merged, can the folks in here who could reproduce the issue confirm whether that resolves the issue?

I've posted a new master-branch build to https://oznogon.com/ee/EE-20200309-win32.zip to help test. Note that issue #769 will cause the server to crash this build during networked client/server tests.

**Comment by nigelkennington** [comment] 2020-03-09 09:12
Using the build you provided, that does indeed fix the crash, at least for me.

**Closed** 2020-03-09 11:49 UTC
