### ISSUE TITLE
Game master chat flickers and causes game to crash

### ISSUE THREAD

**Issue by Piglit** [daid/EmptyEpsilon#1754] opened 2022-06-05 13:12 UTC
I ran into some issues with the gm-chat:

* Dragging the GM-Chat window around does not work well - it always attaches to the nearest edge of the screen.
* The text in the input field flickers
* When answering after a message a player typed, the game crashes

Tested with EE-2022.03.16 using Xanstas sandbox scenario. (In the scenario it is possible for the players to start the chat with the gm)

**Comment by daid** [comment] 2022-06-05 15:12
The crash bug should be fixed on master, and can be prevented by clicking on the text field after pressing send/return. Other bits I will have to investigate

**Comment by hemmond** [comment] 2023-03-02 00:19
Can confirm it is fixed on current master. This issue can be closed.

**Comment by hemmond** [comment] 2023-03-02 00:27
Checked on current GIT Master HEAD. Could not reproduce any of the issues mentioned before. If @Piglit doesn't see the issue still persist, then I'd recommend closing this issue.

**Closed** 2023-03-02 13:33 UTC
