### ISSUE TITLE
Various "problems" with the .po translation

### ISSUE THREAD

**Issue by muerteFR** [daid/EmptyEpsilon#1256] opened 2021-01-05 19:05 UTC
I notice on the last compiled (today) version that there are several texts which are not translated :

**1. RESOLVED**
"**Self Destruct Activated!**" in selfDestructEntry.cpp (Ingenierie and Ingenierie+) 
The fr.po translation does not work, but the it.po does. After watching I really don't understand why, it seems ok in fr.po : 
#: src/screenComponents/selfDestructEntry.cpp:22
msgid "Self destruct activated!"
msgstr "Autodestruction activee !"

**2. RESOLVED**  
 "**ADV. Striker**" in Science Database (classe Starfighter)
The fr.po translation doesn't just work on the ship name and works well on the description.
I just observed in ShipTemplates_Old.lua that Setclass and SetModel were reversed unlike the other lines.

**3. RESOLVED**  
 **In the GM console, the names of the ships** to be created are not translated.

**4. RESOLVED**  
 I can't find anywhere (.cpp and .lua) where translate the stations to be created **in GM: "Huge station", "small station",** ...

**5.  RESOLVED**
 #1257   I don't know where to find where translate **the systems in the hacking console:** In Target system: "Beam weapons," "Maneuvering "etc

**6. RESOLVED** 
#1258   Where to translate "**Visual Asteroide**" from the GM console in Create.

7. Where to translate in the GM console always: the indications at the top right? "**Callsign", "Shield", "Hull", "position", "Orders"** Some are already translated as "Time elapsed"

8. Still in GM, the orders at the bottom right are translated but at the top right they are not : (**"roaming", Idle", "Defend location"** etc.

If it's within my reach I will make the changes myself, but I think for the most part I couldn't help because I'm not a developer.

**Comment by oznogon** [comment] 2021-01-06 09:13
It would be easier to track and comment on these problems if they were separate issue tickets in GitHub.

> "Self destruct activated!" in selfDestructEntry.cpp (Ingenierie and Ingenierie+)

<img width="902" alt="Screen Shot 2021-01-06 at 12 34 21 AM" src="https://user-images.githubusercontent.com/19192104/103747111-ffd93800-4fb6-11eb-9c6b-b44b24291c1b.png">

Needs separate research from the other problems in this issue. This appears to be a GuiLabel, and other GuiLabels are translated, so the problem is unclear.

> "Adv. Striker" in Science Database (classe Starfighter) The fr.po translation doesn't just work on the ship name

<img width="1177" alt="Screen Shot 2021-01-06 at 12 36 11 AM" src="https://user-images.githubusercontent.com/19192104/103747256-3747e480-4fb7-11eb-8fb3-d6a7626b6782.png">

Needs separate research from the other problems in this issue.

Both of the above issues would benefit from increased debug logging around i18n functionality.

--

> Where to translate "Visual Asteroide" from the GM console in Create.

```
#: src/screens/gm/objectCreationView.cpp:72
msgctxt "create"
msgid "Visual Asteroid"
msgstr ""
```

A brief test confirms a `msgstr` value added here is used by the GM object creation view.

--

Other features specific to the GM screen have not been updated to output locale-specific strings. For instance, both of these problems need further research to determine whether they need to be broken down into separate work or can be addressed by the same fix:

> I can't find anywhere (.cpp and .lua) where translate the stations to be created in GM: "Huge station", "Small station", ... In the GM console, the names of the ships to be created are not translated.

The ObjectCreationView space station and ship lists are likely related to `ShipTemplate::getTemplateNameList()`, which is called by ObjectCreationView for the lists of station, playership, and ship creation buttons. Locale names are not retrieved for the list items.

> Where to translate in the GM console always: the indications at the top right? "Callsign", "Shield", "Hull", "position", "Orders" Some are already translated as "Time elapsed" ... Still in GM, the orders at the bottom right are translated but at the top right they are not : ("roaming", Idle", "Defend location" etc.

This is the `selection_info` object in GameMasterScreen:

https://github.com/daid/EmptyEpsilon/blob/0a40f22f4694e8bf81656eb2a1173f77237c0d40/src/screens/gm/gameMasterScreen.cpp#L295-L334

The information comes from `SpaceObject::getGMInfo()`, which is used only by the GM screen. For ships, the pertinent override is in ShipTemplateBasedObject, which returns an `unordered_map` of non-localized strings, and are keyed on those strings as well:

https://github.com/daid/EmptyEpsilon/blob/5c37189e3c1075bbfe161c437195ff78ade39bb5/src/spaceObjects/shipTemplateBasedObject.cpp#L255-L266

`selection_info` relies on at least one hardcoded string as a key (`selection_info["Position"]`).

**Comment by Xansta** [comment] 2021-01-06 20:27
Is there a better way to refer to template than by name?

**Comment by oznogon** [comment] 2021-01-06 20:51
I'm honestly not sure, I don't have much experience with how localization interacts with scenarios. But string comparisons that rely on English names have already caused problems like #1155

**Comment by oznogon** [comment] 2021-01-06 20:57
It might be as simple as wrapping those scenario strings in `_()` functions, and making sure the scenario .pos exactly match the strings in the locale .po. It might help to find another way to associate station sizes that doesn't always rely on a string comparison.

**Comment by gcask** [comment] 2021-01-07 20:32
Would it be possible for scripts to lean on the `msgid`s in some fashion?

**Comment by oznogon** [comment] 2021-01-13 01:49
>     "Self Destruct Activated!" in selfDestructEntry.cpp (Ingenierie and Ingenierie+)
>    The fr.po translation does not work, but the it.po does. After watching I really don't understand why, it seems ok in fr.po :
>    #: src/screenComponents/selfDestructEntry.cpp:22
>    msgid "Self destruct activated!"
>    msgstr "Autodestruction activee !"

This appears fixed on master.

<img width="907" alt="Screen Shot 2021-01-12 at 5 47 52 PM" src="https://user-images.githubusercontent.com/19192104/104395848-7b2e7280-54fe-11eb-8fda-165b0b092183.png">

**Closed** 2021-03-15 15:51 UTC
