### ISSUE TITLE
Touchscreen & Windows 10

### ISSUE THREAD

**Issue by jonathanbucci** [daid/EmptyEpsilon#464] opened 2017-06-19 22:18 UTC
Hello. Running Windows 10 on a Microsoft SurfaceBook and a cheap windows tablet. Both have a weird touchscreen behavior. When using the touchscreen, all onscreen buttons must be double-tapped to select/activate them. With mouse it is a single click. This problem doesn't exist in the Android build. Anyone  else having this?

EE Version 20170506
Windows is completely up to date as of 6/19/17. Windows 10.0.15063 Build 15063

**Comment by oznogon** [comment] 2017-06-19 22:49
I have this issue on Win 7 with a Lenovo P40 Yoga, which has an optional built-in active digitizer touchscreen input in addition to the standard touchscreen. The active stylus works as expected, but I have to double-tap or tap-and-drag to get finger input recognized.

IIRC this is related to SFML, but I can't find a ticket for it.

**Comment by jonathanbucci** [comment] 2017-06-20 18:53
Yep. That is the exact behavior I'm getting too. Mouse works fine. Surface Pen and Touching with finger requires double-tap or tap and drag to select menus or operate ships. I also have the audio device issues but that has it's own ticket. I agree that it seems SFML related but I have no evidence to support my theory.

**Comment by oznogon** [comment] 2017-12-23 19:23
Still having this issue with Win10 on a new Yoga 720, both touchscreens with active pen input like the Surface/Surface Book, and I've also had this issue with other games and apps using SFML input.

This doesn't seem to affect other game engines, and doesn't affect these devices when running off netboot or Ubuntu 16.04.

**Comment by oznogon** [comment] 2017-12-23 22:59
A relevant SFML issue might be https://github.com/SFML/SFML/pull/912, which would add support for touch API in Win7 and newer. But that branch hasn't seen commits since March or new comments since September, so I don't know if it'll land in SFML 2.5.

**Comment by oznogon** [comment] 2017-12-23 23:08
Other SFML forum threads reporting this:

- [No touch events on Surface devices](https://en.sfml-dev.org/forums/index.php?topic=21016.msg150317)
- [Windows 10 touch screen](https://en.sfml-dev.org/forums/index.php?topic=22472.msg157903)

Both suggest using the `feature/windows_touch` branch of SFML, but @daid is reporting on [bridgesim.net](http://bridgesim.net/discussion/comment/3005/#Comment_3005) that SFML 2.4.2 is causing him some build trouble, so I doubt compiling an unmergable out-of-sync branch that's been dead in the water for three months will work any better.

**Comment by daid** [comment] 2017-12-24 11:58
2.4.2 is causing some problems in combination with my build environment. SFML 2.4.2 is fine otherwise.

**Comment by daid** [comment] 2018-01-04 18:51
People following this, in the topic at http://bridgesim.net/discussion/comment/3074/#Comment_3074 we most likely have found the cause of the touch screen issue.
I've re-written the input handling in SeriousProton, and I hope that will fix this problem.

**Comment by daid** [comment] 2018-01-05 13:44
As far as reported on the bridgesim topic, the release of today, 2018-01-05 should fix the windows surface touch related issues.
Please report back if this is not the case, until then, I will close this issue as fixed.

**Closed by daid** 2018-01-05 13:44 UTC

**Comment by jonathanbucci** [comment] 2018-01-05 15:53
Hey Daid,

I did some testing late last night. The only issue I see is using the touchscreen in the pre-station menu. It seems that the click length is longer than the time it takes to change pages. 

Example: Clicking Close Server will also press Close on the next page, exiting EE completely, because they are in the same place on their respective pages. . 

This issue doesn't seem to come up in gameplay, only in the menu. So I'd call this issue 90% resolved.

**Comment by daid** [comment] 2018-01-05 16:32
I'm pretty sure this commit fixes that issue: https://github.com/daid/SeriousProton/commit/5b94e4bc2426b4280b2cdea2f8775d6f9a0a4b32
