### ISSUE TITLE
Android 5" grafic bug

### ISSUE THREAD

**Issue by Faithnall** [daid/EmptyEpsilon#499] opened 2017-12-17 14:07 UTC
Testet Android last Version under Huawei P10 (5" Display)

The Outer Direction Ring is missing under the Helm View. The Science View is mostly Empty.

Her you can see the Helm View Screenshoot under Huawei P10 

[Grafic bug jpg](http://no-brothers.de/empty-epsilon.jpg)

**Comment by daid** [comment] 2017-12-19 16:54
Nothing I can do to fix it. Android will remain a hit&miss depending on the phone. Some tablets also don't render text correctly.

**Comment by oznogon** [comment] 2020-03-01 07:44
Related to/duplicate of #758

**Closed** 2020-03-01 08:22 UTC
